googleinterns/step174-2020

README.md

Workflow was initialized and forked to allow for future pull requests as progress continues.

Updated and personalized README contents.

---

udaykalra/README.md

Local workspace is properly prepared and local issue in which global readme was edited while editing the sub-readme was repaired.

Fixed local dependency issue and prepared workspace

---

.gitignore

The current path to the target folders is incorrect.

Add maven target directories to .gitignore.

---

jelares/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java

I fixed the problem with the out-of-sync master and created a new branch from it, so that this is the only commit in the delta

Jesus: Week 3 Step 1

---

udaykalra/portfolio/pom.xml
udaykalra/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
udaykalra/portfolio/src/main/webapp/index.html
udaykalra/portfolio/src/main/webapp/script.js
udaykalra/portfolio/src/main/webapp/style.css

Implement a comment submission feature. One can test by typing a comment in the field in index.html, submit comment, then fetch comments. Deploy at each step's completion at go/UdayKalra-app .

Week 3 Step Four - Uday

---

udaykalra/portfolio/pom.xml
udaykalra/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
udaykalra/portfolio/src/main/webapp/index.html
udaykalra/portfolio/src/main/webapp/script.js

Complete MVP for the comment feature. Implement persistent storage with DataStore and remove deprecation. Currently deployed at go/UdayKalra-app .

Week 3 Step Five (Completed MVP) - Uday (Merge 2,3,4 Prior !)

---

agcaballero/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
agcaballero/portfolio/src/main/webapp/about.html
agcaballero/portfolio/src/main/webapp/comments.html
agcaballero/portfolio/src/main/webapp/contact.html
agcaballero/portfolio/src/main/webapp/gallery.html
agcaballero/portfolio/src/main/webapp/index.html
agcaballero/portfolio/src/main/webapp/nav.html
agcaballero/portfolio/src/main/webapp/script.js
agcaballero/portfolio/src/main/webapp/style.css

Make sure the merges did not affect website. Edit nav bar to include all relevant pages. Add nav bar and footer to all page files. Fix style of files including CSS.
Note: the changes made can be seen as they have all been deployed on go/agcaballero-step-2020.

Edit files to smooth edges of merges from different branches 

---

agcaballero/portfolio/src/main/webapp/index.html

Fix the formatting of an HTML file (needed to do manually due to issues with command line).

Fix formatting of index.html

---

udaykalra/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
udaykalra/portfolio/src/main/java/com/google/sps/servlets/DeleteDataServlet.java
udaykalra/portfolio/src/main/webapp/Contact.html
udaykalra/portfolio/src/main/webapp/Projects.html
udaykalra/portfolio/src/main/webapp/Resume.html
udaykalra/portfolio/src/main/webapp/index.html
udaykalra/portfolio/src/main/webapp/script.js
udaykalra/portfolio/src/main/webapp/style.css

Add comment limiter and deletion features.

Week 3 Step 6 - Uday

---

udaykalra/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
udaykalra/portfolio/src/main/java/com/google/sps/servlets/EndorsedDataServlet.java
udaykalra/portfolio/src/main/java/com/google/sps/servlets/PollDataServlet.java
udaykalra/portfolio/src/main/webapp/Contact.html
udaykalra/portfolio/src/main/webapp/Projects.html
udaykalra/portfolio/src/main/webapp/Resume.html
udaykalra/portfolio/src/main/webapp/index.html
udaykalra/portfolio/src/main/webapp/script.js
udaykalra/portfolio/src/main/webapp/style.css

Implemented Maps API to show university on contact page and Charts API to endorse skills on resume page.

Week 4 APIs(Maps/Charts) - Uday

---

udaykalra/portfolio/src/main/webapp/Contact.html
udaykalra/portfolio/src/main/webapp/Projects.html
udaykalra/portfolio/src/main/webapp/Resume.html
udaykalra/portfolio/src/main/webapp/index.html
udaykalra/portfolio/src/main/webapp/script.js
udaykalra/portfolio/src/main/webapp/style.css

Added heads in html, changed color structure in css, and added JS features to satisfy the linter.

Fix minor portfolio issues for make validate.

---

backstory/pom.xml
backstory/src/main/java/com/google/sps/servlets/PerspectiveFilterServlet.java
backstory/src/main/webapp/WEB-INF/appengine-web.xml
backstory/src/main/webapp/script.js
backstory/src/main/webapp/style.css

Add the file system and some sample files for Backstory project (e.g. add appropriate dependencies to pom.xml, create a style.css and script.js file). Additionally, add file for Perspective filter (although curently it has no substantive code in it).

7/22: Add file system for the project and basic first file for Perspective filter

---

agcaballero/portfolio/src/main/webapp/contact.html

Remove outdated code (script call for wrong file and call to old validation method).

7/22: Remove outdated code

---

udaykalra/walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
udaykalra/walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/MeetingRequest.java
udaykalra/walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/servlets/GetEventsServlet.java
udaykalra/walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/servlets/QueryServlet.java
udaykalra/walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java

Initial query function complete with all tests passing successfully.

Query Function prior to Optional Attendees - Uday

---

agcaballero/walkthroughs/week-5-tdd/intro/src/main/java/com/google/sps/Greeter.java
agcaballero/walkthroughs/week-5-tdd/intro/src/test/java/com/google/sps/GreeterTest.java
agcaballero/walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java

Build out the query function with my chosen algorithm for finding time ranges (create a boolean[] of minutes and then iterate through events and mark the part of the minute[] that overlaps with an event with necessary attendees as false, then at end, iterate through and return the TimeRanges of the sections that were true if they were sufficiently long enough).

7/16: Implement query function (without optional participants)

---

udaykalra/walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
udaykalra/walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java

Add functionality for optional attendees and 5 corresponding tests.

UK Query Function with Optional Attendees

---

backstory/src/main/java/com/google/sps/perspective/PerspectiveDecision.java

Add the PerspectiveDecision class (a container for the decision returned by Perspective).

8/4: Add PerspectiveDecision Class

---

backstory/src/main/java/com/google/sps/perspective/NoAppropriateStoryException.java
backstory/src/main/java/com/google/sps/perspective/PerspectiveDecision.java
backstory/src/main/java/com/google/sps/perspective/PerspectiveManager.java
backstory/src/main/java/com/google/sps/perspective/PerspectiveManagerImpl.java

Add PerspectiveManager interface and the custom exception it throws (NoAppropriateStoryException). Add a stubbed implementation of PerspectiveManager which returns a default PerspectiveDecision instance.

8/4: Add PerspectiveManager interface & stubbed implementation of PerspectiveManager

---

backstory/src/main/java/com/google/sps/perspective/PerspectiveAPIFactory.java
backstory/src/main/java/com/google/sps/perspective/PerspectiveAPIFactoryImpl.java
backstory/src/main/java/com/google/sps/perspective/PerspectiveManager.java

Add the PerspectiveAPIFactory interface and implementation. 
Note: Discussed with Joe, and decided that the PerspectiveAPIFactoryImpl class did not need testing.

8/4: Add PerspectiveAPIFactory interface & implementation

---

backstory/src/main/java/com/google/sps/perspective/PerspectiveAPIFactory.java
backstory/src/main/java/com/google/sps/perspective/PerspectiveAPIFactoryImpl.java

Reverts googleinterns/step174-2020#134

Revert "Revert "8/4: Add PerspectiveAPIFactory interface & implementation""

---

backstory/src/main/java/com/google/sps/perspective/PerspectiveAPIFactory.java
backstory/src/main/java/com/google/sps/perspective/PerspectiveAPIFactoryImpl.java
backstory/src/main/java/com/google/sps/perspective/PerspectiveManager.java

Merge an [approved PR](https://github.com/googleinterns/step174-2020/pull/129) into master. 
Note: I forgot to rebase a PR correctly prior to merging, so now I need a new PR to merge.

8/4: Merge already approved of changes into master 

---

backstory/src/demo/webapp/demos.html
backstory/src/demo/webapp/gpt2-demo.html
backstory/src/demo/webapp/gpt2.js
backstory/src/demo/webapp/perspective-demo.html
backstory/src/main/webapp/index.html
backstory/src/main/webapp/style.css

Add HTML and CSS for GPT-2 demo. Update other current pages in order to standardize design across website.

8/6: Add the HTML/CSS (& empty JS) for GPT-2 Demo

---

backstory/src/main/java/com/google/sps/perspective/PerspectiveStoryAnalysisManager.java
backstory/src/main/java/com/google/sps/perspective/data/PerspectiveDecision.java
backstory/src/test/java/com/google/sps/perspective/PerspectiveAPIClientTest.java

Run `make pretty` and `make validate` on all files for Perspective project. Upload updated files.
Note: needed because I forgot to run `make pretty` on some files.

8/10: Make files pretty

---

backstory/src/main/webapp/index.html
backstory/src/main/webapp/script.js
backstory/src/main/webapp/style.css

Add description to front page of website to make it clear how to use it. Update styling accordingly. Resovle issue #172 .
Visuals:

8/20: Add description to front page of website

---

backstory/src/main/java/com/google/sps/perspective/data/ContentDecisions.java
backstory/src/main/webapp/index.html
backstory/src/main/webapp/script.js

#178 was merged into image-validation but not master, so this PR is just to merge it into master. That PR has already been approved.

8/21: Merge already-approved changes (add description) into master

---

backstory/src/main/java/com/google/sps/servlets/AnalyzeImageServlet.java

Corrects the servlet that calls PromptManager by also passing in the locations found by Vision. Tests not pass until #190 and #191 have been merged (as well as any base branches of these PRs). Will finally resolve #118.

8/27: Correct call to PromptManager to reflect integration of image analysis

---

backstory/src/main/java/com/google/sps/story/PromptManager.java
backstory/src/test/java/com/google/sps/story/PromptManagerTest.java

Update prompt manager so that it takes keywords and locations. Update tests accordingly. Add formatted location (location chosen is first location in list) to the prompt. Add tests accordingly. Integrates features built in #190 and helps resolve #118.

8/27: Add Image Location into Prompt
